from enum import Enum


class RaceEvent(Enum):
    RACER_ENTER = 0
    RACER_UNENTER = 1
    RACER_READY = 2
    RACER_UNREADY = 3
    RACER_FINISH = 4
    RACER_UNFINISH = 5
    RACER_FORFEIT = 6
    RACER_UNFORFEIT = 7

    RACE_BEGIN_COUNTDOWN = 101
    RACE_CANCEL_COUNTDOWN = 102
    RACE_BEGIN = 103
    RACE_END = 104
    RACE_CANCEL_FINALIZE = 105
    RACE_FINALIZE = 106
    RACE_CANCEL = 107
    RACE_PAUSE = 108
    RACE_UNPAUSE = 109

    ADD_EXTRANEOUS = 201
    CHANGE_RULES = 202
