"""
High-level module for the standard Condorbot (Event Server) config.


Package Requirements
--------------------
gsheet
league
    match
        user
        botbase
        util
stats
stream


Dependencies
------------
condoradminchannel
    botbase/
        cmd_seedgen
        botchannel
    gsheet/
        cmd_sheet
    league/
        cmd_league
    user/
        cmd_user
condormainchannel
    botbase/
        cmd_admin
    league/
        cmd_league
        cmd_leaguestats
    match/
        cmd_match
    user/
        cmd_user
condormgr
    botbase/
        necroevent
        manager
    gsheet/
        cmd_sheet
        sheetlib
        matchupsheet
        standingssheet
    league/
        leaguemgr
        leaguestats
    match/
        matchutil
        match
        matchroom
    stream/
        vodrecord
    util/
        server
        singleton
        strutil
        rtmputil
condorpmchannel
    botbase/
        cmd_admin
        botchannel
    league/
        leaguestats
    match/
        cmd_match
    user/
        cmd_user
"""